const foodImages: { [key: string]: any } = {
  fufu: require('./fufu.jpg'),
  waakye: require('./waakye.jpg'),
  gobe: require('./gobe.jpg'),
  gob3: require('./gobe.jpg'),
  banku: require('./banku.jpg'),
  etor: require('./etor.jpg'),
  kelewele: require('./kelewele.jpg'),
  jollof: require('./jollof.jpg'),
  fante_kenkey: require('./fante_kenkey.jpg'),
  ga_kenkey: require('./ga_kenkey.jpg'),
  kokonte: require('./kokonte.jpg'),
  plain_rice: require('./plain_rice.jpg'),
  plantain: require('./plantain.jpg'),
  rice_balls: require('./rice_balls.jpg'),
  tuo_zaafi: require('./tuo_zaafi.jpg'),
  yam: require('./yam.jpg'),
  unkown: require('./unknown_food.jpg'),

  'fante kenkey': require('./fante_kenkey.jpg'),
  kenkey: require('./fante_kenkey.jpg'),
  'ga kenkey': require('./ga_kenkey.jpg'),
  'plain rice': require('./plain_rice.jpg'),
  rice: require('./plain_rice.jpg'),
  'rice and stew': require('./plain_rice.jpg'),
  'rice balls (omo tuo)': require('./rice_balls.jpg'),
  'omo tuo': require('./rice_balls.jpg'),
  'rice balls': require('./rice_balls.jpg'),
  'etor (oto)': require('./etor.jpg'),
  oto: require('./etor.jpg'),
  'boiled plantain (ampesie)': require('./plantain.jpg'),
  ampesie: require('./plantain.jpg'),
  'jollof rice': require('./jollof.jpg'),
  'tuo zaafi': require('./tuo_zaafi.jpg'),
  'tuo zaafi (tz)': require('./tuo_zaafi.jpg'),
  tz: require('./tuo_zaafi.jpg'),
  'boiled yam (ampesie)': require('./yam.jpg'),
};

export default foodImages;
