import { StyleSheet } from 'react-native';
import { Platform, StatusBar } from 'react-native';
import colors from '.././config/colors';

const HomePageStyles = StyleSheet.create({
  activeButton: {
    backgroundColor: colors.tertiary,
  },
  analyzeButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginBottom: 10,
  },
  appLogo: {
    width: 30,
    height: 30,
    borderRadius: 50,
  },
  actionContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  cameraButton: {
    backgroundColor: colors.tertiary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    paddingHorizontal: 30,
    marginTop: 10,
    height: 50,
    borderRadius: 10,
  },
  uploadButton: {
    backgroundColor: colors.tertiary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    paddingHorizontal: 15,
    marginTop: 10,
    height: 50,
    borderRadius: 10,
  },
  capturedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#ef4444',
    borderRadius: 20,
    padding: 5,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  content: {
    flex: 1,
    // justifyContent: 'center',
    paddingHorizontal: 20,
  },
  descriptionText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#333',
    marginBottom: 20,
  },
  disabledSearchButton: {
    backgroundColor: '#A5D6B4',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    // borderBottomColor: '#FFF',
    borderBottomColor: '#b9b8b8ff',
    // borderBottomColor: colors.tertiary,
    backgroundColor: colors.secondary,
  },
  imagePreviewContainer: {
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 16,
  },
  imageWrapper: {
    position: 'relative',
    width: '100%',
    aspectRatio: 1,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 16,
  },
  safeContainer: {
    flex: 1,
    backgroundColor: colors.secondary,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  title: {
    fontSize: 22,
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  coloredText: {
    fontSize: 22,
    fontFamily: 'Poppins-SemiBold',
    color: '#4CAF50',
  },
  question: {
    fontSize: 18,
    marginBottom: 20,
    marginTop: 20,
    textAlign: 'center',
    color: colors.gray,
  },
  input: {
    borderWidth: 0.5,
    borderColor: '#ccc',
    backgroundColor: colors.secondary,
    height: 50,
    padding: 10,
    marginTop: 20,
    borderRadius: 5,
  },
  inputWrapper: {
    position: 'relative',
    justifyContent: 'center',
  },
  innerContainer: {
    backgroundColor: colors.secondary,
    borderRadius: 10,
    padding: 20,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#ccc',
    alignItems: 'center',
  },
  outerContainer: {
    margin: 16,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ccc',
    width: '100%',
    alignSelf: 'center',
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleButton: {
    width: 70,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 20,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 8,
  },
  uploadButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  image: {
    width: 200,
    height: 200,
    marginTop: 20,
    alignSelf: 'center',
    borderRadius: 10,
  },
  pIcon: {
    width: 35,
    height: 35,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#FFF',
    backgroundColor: '#EEE',
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 5,
    backgroundColor: 'rgba(0, 255, 0, 0.6)',
    borderRadius: 3,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  searchContainer: {
    paddingHorizontal: 10,
    marginTop: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#E0E0E0',
    paddingBottom: 16,
    paddingTop: 5,
    elevation: 1,
  },
  searchIconButton: {
    position: 'absolute',
    right: 3,
    top: 23,
    backgroundColor: '#4CAF50',
    padding: 13,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggestionText: {
    marginTop: 5,
    color: '#888',
    fontSize: 12,
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 4,
    justifyContent: 'space-between',
    marginTop: 20,
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
  },
  toggleText: {
    marginLeft: 6,
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    color: colors.tertiary,
    fontWeight: 'bold',
  },
  toggleTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  topIcon: {
    marginBottom: 12,
  },
});

export default HomePageStyles;
