import { StyleSheet } from 'react-native';
import { Platform, StatusBar } from 'react-native';
import colors from '.././config/colors';

const HomePageStyles = StyleSheet.create({
  activeButton: {
    backgroundColor: '#4CAF50',
    elevation: 1,
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2,
  },
  analyzeButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginBottom: 10,
  },
  appLogo: {
    width: 30,
    height: 30,
    borderRadius: 50,
  },
  actionContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  cameraButton: {
    backgroundColor: colors.tertiary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    paddingHorizontal: 30,
    marginTop: 10,
    height: 50,
    borderRadius: 10,
  },
  uploadButton: {
    backgroundColor: colors.tertiary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    paddingHorizontal: 15,
    marginTop: 10,
    height: 50,
    borderRadius: 10,
  },
  capturedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#ef4444',
    borderRadius: 20,
    padding: 5,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.secondary,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  descriptionText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#333',
  },
  disabledSearchButton: {
    backgroundColor: '#81C784',
    opacity: 0.7,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.secondary,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
  },
  imagePreviewContainer: {
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 16,
  },
  imageWrapper: {
    position: 'relative',
    width: '100%',
    aspectRatio: 1,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 16,
  },
  safeContainer: {
    flex: 1,
    backgroundColor: colors.secondary,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  title: {
    fontSize: 22,
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
  },
  coloredText: {
    fontSize: 22,
    fontFamily: 'Poppins-SemiBold',
    color: '#4CAF50',
  },
  question: {
    fontSize: 20,
    marginBottom: 25,
    marginTop: 25,
    textAlign: 'center',
    color: '#2E7D32',
    fontWeight: '600',
    paddingHorizontal: 10,
    lineHeight: 28,
  },
  input: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#E8F5E8',
    backgroundColor: '#F8FDF8',
    height: 55,
    paddingLeft: 50,
    paddingRight: 45,
    borderRadius: 12,
    fontSize: 16,
    color: '#333',
  },
  inputWrapper: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  innerContainer: {
    backgroundColor: colors.secondary,
    borderRadius: 10,
    padding: 20,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#ccc',
    alignItems: 'center',
  },
  outerContainer: {
    margin: 16,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ccc',
    width: '100%',
    alignSelf: 'center',
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleButton: {
    width: 70,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 20,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 8,
  },
  uploadButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  image: {
    width: 200,
    height: 200,
    marginTop: 20,
    alignSelf: 'center',
    borderRadius: 10,
  },
  pIcon: {
    width: 35,
    height: 35,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#FFF',
    backgroundColor: '#EEE',
  },
  scanOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 5,
    backgroundColor: 'rgba(0, 255, 0, 0.6)',
    borderRadius: 3,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  searchContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#E8F5E8',
    paddingBottom: 25,
    paddingTop: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
  },
  searchIconButton: {
    position: 'absolute',
    right: 3,
    top: 23,
    backgroundColor: '#4CAF50',
    padding: 13,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggestionText: {
    marginTop: 5,
    color: '#888',
    fontSize: 12,
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 6,
    justifyContent: 'space-between',
    marginTop: 25,
    marginBottom: 5,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 1.5,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    flex: 1,
    justifyContent: 'center',
  },
  toggleText: {
    marginLeft: 8,
    fontSize: 15,
    fontWeight: '600',
    color: colors.tertiary,
  },
  toggleTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  topIcon: {
    marginBottom: 12,
  },
  searchSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  searchIcon: {
    position: 'absolute',
    left: 15,
    zIndex: 1,
  },
  clearButton: {
    position: 'absolute',
    right: 15,
    zIndex: 1,
    padding: 5,
  },
  searchButton: {
    backgroundColor: '#4CAF50',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginBottom: 20,
    gap: 8,
  },
  searchButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  suggestionContainer: {
    marginTop: 5,
  },
  suggestionTitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
    fontWeight: '500',
  },
  suggestionTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  suggestionTag: {
    backgroundColor: '#E8F5E8',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D4E6D4',
  },
  suggestionTagText: {
    color: '#4CAF50',
    fontSize: 12,
    fontWeight: '500',
  },
  cameraContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#E8F5E8',
    paddingBottom: 20,
    paddingTop: 15,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
  },
  cameraSection: {
    alignItems: 'center',
    marginBottom: 15,
  },
  cameraActionContainer: {
    marginBottom: 15,
  },
  primaryCameraButton: {
    backgroundColor: '#4CAF50',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    gap: 8,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  dividerText: {
    color: '#999',
    fontSize: 14,
    paddingHorizontal: 15,
    fontWeight: '500',
  },
  secondaryCameraButton: {
    backgroundColor: '#F8FDF8',
    borderWidth: 2,
    borderColor: '#E8F5E8',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    gap: 8,
  },
  secondaryButtonText: {
    color: '#4CAF50',
    fontSize: 16,
    fontWeight: '600',
  },
  cameraHintContainer: {
    marginTop: 8,
  },
  cameraHintTitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
    fontWeight: '500',
  },
  cameraHints: {
    marginLeft: 10,
  },
  cameraHintText: {
    color: '#888',
    fontSize: 12,
    marginBottom: 4,
    lineHeight: 16,
  },
});

export default HomePageStyles;
